### PR TITLE
Refresh plugin 2023

### PR DESCRIPTION
**Pull request by jonesbusy**
This is a normal plugin refresh : https://www.jenkins.io/doc/developer/tutorial-improve/

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jonesbusy** [comment]
Need an admin to replay the build to allow changes on Jenkinsfile

**Comment by jonesbusy** [comment]
Hi @pit3k what is the status of this plugin ? Is it up for adoption ? I'm volunteer to keep it up to date

Best regards,

**Comment by pit3k** [comment]
Hi @jonesbusy , yes, please feel free to adopt it, I no longer maintain it. Is there anything I need to do?

**Comment by jonesbusy** [comment]
> Hi @jonesbusy , yes, please feel free to adopt it, I no longer maintain it. Is there anything I need to do?

Hi, thanks. 

Nothing to do on your side, I've open a PR here https://github.com/jenkins-infra/repository-permissions-updater/pull/3365#issuecomment-1596050526

**Comment by olhado** [comment]
@jonesbusy thanks again for adopting this old plugin!

**Pull request merged**
